[workspace]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64", "osx-64", "osx-arm64"]

[dependencies]
python = "3.11.*"
biopython = ">=1.83,<2"
requests = ">=2.31,<3"
hmmer = "*"
pip = "*"

[tasks]
validate = "bash scripts/validate.sh"
itak = "python -m itak"
