{% set version = "2.0.7" %}

package:
  name: itak
  version: {{ version }}

source:
  url: https://github.com/kentnf/iTAK/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 6f02223479a1e07750eeaccd5e7e5c31ed354053d3912edd999a0424b2595ea9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=68
  run:
    - python >=3.8
    - biopython >=1.83
    - requests >=2.31.0
    - hmmer

test:
  commands:
    - itak --help
    - python -m itak db path --target

about:
  home: https://github.com/kentnf/iTAK
  summary: Plant transcription factor, transcriptional regulator, and protein kinase identifier and classifier
  license: MIT
  license_file: LICENSE
  doc_url: https://github.com/kentnf/iTAK/wiki
  dev_url: https://github.com/kentnf/iTAK

extra:
  recipe-maintainers:
    - kentnf
